---
title: "CV"
author: Haydeé Peruyero
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr)
library(knitr)
source("cv_printing_functions.r")

# Carga los datos de tu hoja de hoja de cálculo de google
#En este chunk sólo modifica la dirección de tu CV
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1rLDqEB2n3gZVBcBtIVpiq1H8S_zSJJIyFsthm74R04c/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
 )

```


```{r}
# Corrige la alinacion de los puntos
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================
```{r}
## Construya una red interactiva de puestos coloreados por sección
# y conectados si ocurrieron en el mismo año
#datadrivencv::build_network_logo(CV$entries_data)
```



Contact {#contact}
--------------------------------------------------------------------------------
```{r informacion de contacto}
CV %>% print_contact_info()
```

<br>


Programming Languages {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_programming_languages()
```


Languages {#languages}
--------------------------------------------------------------------------------

```{r}
CV %>% print_languages()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).  

The source code is available at [HaydeePeruyero/CV](https://github.com/HaydeePeruyero/CV) and is powered by [nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

A. Haydeé Contreras Peruyero {#title} 
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

Appointments 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('appointments')
```

Publications 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```


Preprints 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('preprints')
```


<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Teaching Experience 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```


Talks and Posters 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('talks_and_posters')
```

Science Communication {
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('science_communication')
```

Research Experience 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```

Awards
--------------------------------------------------------------------------------
```{r}
CV %<>% print_section('awards')
```


Synergistic Activities
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('synergistic_activities')
```




```{r}
CV %<>% print_links()
```




